# -*- coding: utf-8 -*-
"""Untitled1 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18aoTAd_4TpP_4c_fwy2AI598bDA97Mh7
"""

!pip install fastapi uvicorn pyngrok openai-whisper nest_asyncio ffmpeg-python

!pip install faster-whisper

from fastapi import FastAPI, UploadFile, WebSocket
import whisper
from fastapi.middleware.cors import CORSMiddleware
import tempfile
from pyngrok import ngrok
import uvicorn
import nest_asyncio
import threading
import os
import ffmpeg
# from faster_whisper import WhisperModel
# model = WhisperModel("base", device="cuda")


# Add ngrok auth token (replace with yours)
!ngrok config add-authtoken 35CspdefHTi7ZockpcyjrWmriLQ_5dgwtQbwJXNRyWQPGTznd

app = FastAPI()
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # or ["http://localhost:3000"]
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)
model = whisper.load_model("small",device="cuda")

@app.post("/transcribe")
async def transcribe_audio(file: UploadFile):
    with tempfile.NamedTemporaryFile(delete=False, suffix=".wav") as temp_audio:
        temp_audio.write(await file.read())
        temp_audio.flush()
        result = model.transcribe(temp_audio.name)
    os.remove(temp_audio.name)
    return {"text": result["text"]}


@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    await websocket.accept()
    audio_data = b""

    try:
        while True:
            chunk = await websocket.receive_bytes()
            audio_data += chunk

            # Transcribe chunk
            with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmp:
                tmp.write(audio_data)
                tmp.flush()
                result = model.transcribe(tmp.name)
            await websocket.send_text(result["text"])
    except Exception:
        await websocket.close()

public_url = ngrok.connect(8000)
print("🚀 Public URL:", public_url.public_url)
print("🔗 WebSocket:", f"wss://{public_url.public_url.split('//')[1]}/ws")

# Allow FastAPI inside Colab
nest_asyncio.apply()

# Run FastAPI in background
def run_app():
    uvicorn.run(app, host="0.0.0.0", port=8000)

thread = threading.Thread(target=run_app)
thread.start()

from pyngrok import ngrok

# Kill all active tunnels
ngrok.kill()
# print("✅ All old ngrok tunnels closed. Now you can create a new one.")

!kill -9 $(lsof -t -i:8000)